default_language_version:
  python: python3.13.2
fail_fast: True
default_stages: [pre-push]
repos:
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: [--skip=*.js, --skip=*.xml, --skip=*.html, --skip=*.css, --skip=*.svg]
    stages: [pre-commit, pre-push]
    always_run: true
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.0
  hooks:
  - id: ruff-format
    name: ruff-format-src
    args: [./src]
    stages: [pre-commit, pre-push]
    always_run: true
  - id: ruff-format
    name: ruff-format-tests
    args: [./tests]
    stages: [pre-commit, pre-push]
    always_run: true
  - id: ruff-check
    name: ruff-check-src
    args: [./src]
    stages: [pre-commit, pre-push]
    always_run: true
  - id: ruff-check
    name: ruff-check-tests
    args: [./tests]
    stages: [pre-commit, pre-push]
    always_run: true
- repo: https://github.com/econchick/interrogate
  rev: 1.7.0  
  hooks:
  - id: interrogate
    name: interrogate-src
    pass_filenames: false
    args: [./src, --verbose, --fail-under=100, --ignore-module, --ignore-init-method]
    stages: [pre-commit, pre-push]
    always_run: true
  - id: interrogate
    name: interrogate-tests
    pass_filenames: false
    args: [./tests, --verbose, --fail-under=100, --ignore-module, --ignore-init-method]
    stages: [pre-commit, pre-push]
    always_run: true
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "ruff"]