[project]
name = "common-precommits"
version = "0.1.0"
description = "base precommit and associated files for projects"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pre-commit>=4.3.0",
]
